env:
  commonjs: true
  es6: true
  node: true
extends: google
parserOptions:
  ecmaVersion: 2018
rules:
  max-len:
    - error
    - code: 100
  require-jsdoc:
    - off
  # linebreak-style: 
  #   ["error", "windows"]
  # semi: 
  #   0
  # brace-style:
  #   [2, "stroustrup", { "allowSingleLine": true }]
  # block-spacing: 
  #   [2, "always"]
  # no-trailing-spaces:
  #   ["error", {"ignoreComments": true}]
    